spring:
  application:
    name: stagiaire-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3308/examen_db
    username: root
    password: mariko745076
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
  instance:
    preferIpAddress: true
server:
  port: 9091
